# Setup
title:               Jean-Elie Pierre
tagline:             'Computer Engineer'
#description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://jepierre.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jean-Elie Pierre
  url:               https://twitter.com/jp_primetime
  email:             info@jepierre.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y


# User settings
user_description: I'm a Computer Engineer with a passion for integrating hardware and software with several years of experience leading large technical projects. I'm a lifelong learner and tinkerer. My interests are in Reinforcement Learning, Computer Vision, Machine Learning, Image Processing, Robotics, Embedded Systems, IoT, DevOps. 
user_title: Computer Engineer
email: emailme@jepierre.com
github_username:  jepierre
twitter_username: jp_primetime
facebook_username: jean.elie.pierre005
linkedin_username: jean-elie-pierre

include: ['_pages']
sass:
    sass_dir: _sass

markdown: kramdown
highlighter: rouge