# Setup
title:               Jean-Elie Pierre
tagline:             'Computer Engineer'
#description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://jepierre.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jean-Elie Pierre
  url:               https://twitter.com/jp_primetime
  email:             info@jepierre.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y


# User settings
user_description: Highly skilled GN&C Engineer with technical management expertise and several years of experience working in the Defense and Space industry solving complex technical systems. Experienced project management professional with a proven track record of leading small and large cross-functional teams in delivering breakthrough Research and Development (R&D) capabilities. Strong research professional with a Ph.D. in Computer Engineering with a focus on coordination and collaboration of multi-agent systems. Areas of expertise include Reinforcement Learning, Machine Learning, Guidance, Navigation and Controls (GN&C); software development in embedded systems (C/C++), Python, TensorFlow, Pytorch, custom PCB design, Altium, NI Labview, robotics simulation, Continuous Integration/Continuous Delivery (CI/CD), DevOps, Computer Vision, and test engineering.
user_title: Computer Engineer
email: emailme@jepierre.com
github_username:  jepierre
twitter_username: jp_primetime
facebook_username: jean.elie.pierre005
linkedin_username: jean-elie-pierre
google_scholar: https://scholar.google.com/citations?hl=en&user=l-t-5pgAAAAJ

include: ['_pages']
sass:
    sass_dir: _sass

markdown: kramdown
highlighter: rouge